services:
  Client:
    #image: ${CONTAINER_REGISTRY_BASE}/r9iotwebserver
    image: Client
    build:
      context: ./Client
      target: Client
      cache_from:
        - Client
    depends_on:
      - Server
    #env_file:
    #  - ./r9iotweb/.env
    ports:
      - 8081:8080
    # Comment out these volumes in production
    volumes:
      - ./Client:/app:rw,cached
      #- /app/node_modules

  Server:
    #image: ${CONTAINER_REGISTRY_BASE}/r9iotwebserver
    image: Server
    build:
      context: ./Server
      target: Server
      cache_from:
        - Server
    depends_on:
      - mysql
    env_file:
      - ./Server/.env
    ports:
      - 8000:8001
    # Comment out these volumes in production
    volumes:
      - ./r9iotwebserver/node_modules:/app/node_modules
      - ./r9iotwebserver:/app:rw,cached
      - ./r9iotwebserver/server/public/gateway-images:/app/dist/public:rw


